### ISSUE TITLE
onder_behandeling_geweestq 2.3 kan nu dubbel voorkomen

### ISSUE THREAD

**Issue by mgraauw** [Nictiz/Geboortezorg#3]
<xsl:for-each select="./onder_behandeling_geweestq">
                <component typeCode="COMP">
                    <xsl:call-template name="template_2.16.840.1.113883.2.4.6.10.90.900958_20161215115649"/>
                </component>
            </xsl:for-each>
            <xsl:if test="algemene_anamnese/*[@value | @code | @nullFlavor]">
                
                <xsl:if test="not(onder_behandeling_geweestq)">

**Comment by weteringac** [comment]
Fixed in commit:  https://github.com/Nictiz/Geboortezorg/commit/25a4a732074d5cd7f2f9045e595e73ef94913ff4
